### ISSUE TITLE
[Android 辅助通道] 无法打开APP

### ISSUE THREAD

**Issue by DarrenHou1993** [TianKong-0512/cordova-plugin-aliyun-push#1]
集成了华为的辅助通道。 能够接收到辅助通道的信息以及弹框。 点击通知 无法进去APP。 黑屏。 进入的是 `com.alipush.PopupPushActivity`   已经配置了 `open_type: "application"` 大佬知道是大概哪里的问题吗。

**Comment by TianKong-0512** [comment]
有修改，等我把修改的代码上传一下。

**Comment by TianKong-0512** [comment]
代码已上传

**Comment by DarrenHou1993** [comment]
好的 感谢大佬。 确实因为这个被拒过。之前找了个临时方案处理的。

**Comment by TianKong-0512** [comment]
我这边的推送暂时还没发现什么问题。有啥问题可以反馈一下，也避免我这边的用户出问题。  
一块使用的同时一块完善一下。
我是搞前端的，android 不太懂，只能慢慢搞。

**Comment by DarrenHou1993** [comment]
@TianKong-0512  恩 好的 下次有问题我及时提醒你。 我就是因为改成 手动 init push 发现辅助通道不能用了。 然后后来我就又改了下 跟你改的差不多。

**Comment by TianKong-0512** [comment]
@DarrenHou1993 好的👌🏻
